# 1. Vector and Matrix
Vector는 크기와 방향을 가지며, 1차원 배열로 표현   
Matrix는 행과 열을 가지며, 2차원 배열로 표현   

# 2. Tensor
Tensor는 복잡한 입출력에 요구되며, 3차원 이상 배열로 표현

In [1]:
import numpy as np

> **1) 0D Tensor**, Scalar

In [2]:
d = np.array(5)
print(d.ndim)
print(d.shape)

0
()


> **2) 1D Tensor**, Vector  

In [3]:
d = np.array([1,2,3,4])
print(d.ndim)
print(d.shape)

1
(4,)


> **3) 2D Tensor**, Matrix

In [4]:
d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(d.ndim)
print(d.shape)

2
(3, 4)


> **4) 3D Tensor**   
> Data Science 분야에서 3차원 이상 배열은 Tensor   
> Text sequence를 나타낼 경우 (samples/batch_size, timesteps, word_dim)으로 구성

> <null>|문장
> :--|:--
> 문서1|I like NLP    
> 문서2|I like DL   
> 문서3|DL is AI

> 단어|One-Hot vector
> :--|:--
> I|[1 0 0 0 0 0]
> like|[0 1 0 0 0 0]
> NLP|[0 0 1 0 0 0]
> DL|[0 0 0 1 0 0]
> is|[0 0 0 0 1 0]
> AI|[0 0 0 0 0 1]

> 인공 신경망 입력으로 사용하고자 문장 벡터화   
> 이는 (3, 3, 6) 크기 3D Tensor
    
> <null>|문장 벡터화   
> :--|:--
> 문서1|[[1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0]]  
> 문서2|[[1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0]]   
> 문서3|[[0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 1]]   

In [5]:
d = np.array([
              [[1,2,3,4,5], [6,7,8,9,10], [10,11,12,13,14]],
              [[15,16,17,18,19], [19,20,21,22,23], [23,24,25,26,27]]
            ])
print(d.ndim)
print(d.shape)

3
(2, 3, 5)


> **5) More Tensors**   
> n차원 Tensor를 합치면 n+1차원 Tensor
> ![More Tensors](https://wikidocs.net/images/page/37001/tensor.png "More Tensors")

# 3. Vector and Matrix Operation
> **1) Addition and Subtraction**

In [6]:
a = np.array([8,4,5])
b = np.array([1,2,3])
print(a+b)
print(a-b)

[9 6 8]
[7 2 2]


In [7]:
a = np.array([ [10,20,30,40], [50,60,70,80] ])
b = np.array([ [5,6,7,8], [1,2,3,4] ])
print(a+b)
print(a-b)

[[15 26 37 48]
 [51 62 73 84]]
[[ 5 14 23 32]
 [49 58 67 76]]


> **2) Dot Product and Multiplication**

In [8]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.dot(a,b))

32


In [9]:
a = np.array([ [1,3], [2,4] ])
b = np.array([ [5,7], [6,8] ])
print(np.matmul(a,b))

[[23 31]
 [34 46]]


# 4. Multiple Linear Regression with Matrix
Multiple Linear Regression   
$$y = w_{1}x_{1} + w_{2}x_{2} + ... + w_{n}x_{n} + b$$   

가중치와 입력 벡터의 내적으로 행렬곱 표현   
$$y = \begin{bmatrix} x_{1}\\x_{2}\\...\\x_{n}\\ \end{bmatrix}\begin{bmatrix} w_{1} w_{2} ... w_{n}\\ \end{bmatrix} + b$$

# 5. Matrix Size Decision
**Minibatch 학습**은 전체 데이터를 m개씩 묶어 작은 그룹으로 분할해 여러 번 처리
$$Y_{m \times j} = X_{m \times n} \times W_{n \times j} + B_{m \times j}$$