# 1. 임의 입력 생성

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN, LSTM, Bidirectional

# 2D 텐서
train_X = [ [0.1,4.2,1.5,1.1,2.8],
            [1.0,3.1,2.5,0.7,1.1],
            [0.3,2.1,1.5,2.1,0.1],
            [2.2,1.4,0.5,0.9,1.1] ]
print(np.shape(train_X))

(4, 5)


In [2]:
# 3D 텐서
train_X = [[ [0.1,4.2,1.5,1.1,2.8],
             [1.0,3.1,2.5,0.7,1.1],
             [0.3,2.1,1.5,2.1,0.1],
             [2.2,1.4,0.5,0.9,1.1] ]]
train_X = np.array(train_X, dtype=np.float32)
print(train_X.shape)

(1, 4, 5)


# 2. SimpleRNN

In [3]:
# return_sequences=False: 마지막 시점 은닉 상태만 반환
rnn = SimpleRNN(3, return_sequences=False)
hidden_state = rnn(train_X)

print('hidden state: {}, shape: {}'.format(hidden_state, hidden_state.shape))

hidden state: [[-0.68955094  0.54317063 -0.11713348]], shape: (1, 3)


In [4]:
# return_sequences=True: 모든 시점 은닉 상태 반환
rnn = SimpleRNN(3, return_sequences=True)
hidden_states = rnn(train_X)

print('hidden states: {}, shape: {}'.format(hidden_states, hidden_states.shape))

hidden states: [[[ 0.9965923   0.98502755 -0.9999048 ]
  [ 0.71638286  0.9953881  -0.9999903 ]
  [-0.71342885  0.95783854 -0.99996275]
  [ 0.8853167   0.9457677  -0.9971411 ]]], shape: (1, 4, 3)


In [5]:
# return_state=True: 마지막 시점 은닉 상태 반환
rnn = SimpleRNN(3, return_sequences=False, return_state=True)
hidden_state, last_state = rnn(train_X)

print('hidden state: {}, shape: {}'.format(hidden_state, hidden_state.shape))
print('last hidden state: {}, shape: {}'.format(last_state, last_state.shape))

hidden state: [[ 0.86037284 -0.25944093 -0.33476368]], shape: (1, 3)
last hidden state: [[ 0.86037284 -0.25944093 -0.33476368]], shape: (1, 3)


In [6]:
rnn = SimpleRNN(3, return_sequences=True, return_state=True)
hidden_states, last_state = rnn(train_X)

print('hidden states: {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('last hidden state: {}, shape: {}'.format(last_state, last_state.shape))

hidden states: [[[-0.9999546  -0.9996182   0.9947555 ]
  [-0.99988747 -0.99994993  0.9325656 ]
  [-0.9998167  -0.9788065   0.06146588]
  [-0.98799706 -0.9894257   0.61460704]]], shape: (1, 4, 3)
last hidden state: [[-0.98799706 -0.9894257   0.61460704]], shape: (1, 3)


# 3. LSTM 

In [7]:
# return_state=True: 마지막 은닉 상태와 셀 상태 반환
lstm = LSTM(3, return_sequences=False, return_state=True)
hidden_state, last_state, last_cell_state = lstm(train_X)

print('hidden state: {}, shape: {}'.format(hidden_state, hidden_state.shape))
print('last hidden state: {}, shape: {}'.format(last_state, last_state.shape))
print('last cell state: {}, shape: {}'.format(last_cell_state, last_cell_state.shape))

hidden state: [[ 0.4043716  -0.05455049 -0.14046316]], shape: (1, 3)
last hidden state: [[ 0.4043716  -0.05455049 -0.14046316]], shape: (1, 3)
last cell state: [[ 0.757271   -0.07010116 -1.6553054 ]], shape: (1, 3)


In [8]:
lstm = LSTM(3, return_sequences=True, return_state=True)
hidden_states, last_state, last_cell_state = lstm(train_X)

print('hidden states: {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('last hidden state: {}, shape: {}'.format(last_state, last_state.shape))
print('last cell state: {}, shape: {}'.format(last_cell_state, last_cell_state.shape))

hidden states: [[[-0.0310893  -0.48796135  0.59102476]
  [-0.05234299 -0.68633175  0.77240866]
  [-0.029691   -0.64991766  0.8034858 ]
  [-0.02367756 -0.82675636  0.85507   ]]], shape: (1, 4, 3)
last hidden state: [[-0.02367756 -0.82675636  0.85507   ]], shape: (1, 3)
last cell state: [[-0.0545646 -1.9746764  2.041984 ]], shape: (1, 3)


# 4. Bidirectional LSTM 

In [9]:
k_init = tf.keras.initializers.Constant(value=0.1)
b_init = tf.keras.initializers.Constant(value=0)
r_init = tf.keras.initializers.Constant(value=0.1)

In [10]:
# return_sequences=True: n번째 시점 정방향, 역방향 은닉 상태가 연결되어 반환
bilstm = Bidirectional(LSTM(3, return_sequences=True, return_state=True,
                            kernel_initializer=k_init, bias_initializer=b_init, recurrent_initializer=r_init))
hidden_states, forward_h, forward_c, backward_h, backward_c = bilstm(train_X)

print('hidden states: {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('forward state: {}, shape: {}'.format(forward_h, forward_h.shape))
print('backward state: {}, shape: {}'.format(backward_h, backward_h.shape))

hidden states: [[[0.35906473 0.35906473 0.35906473 0.7038734  0.7038734  0.7038734 ]
  [0.55111325 0.55111325 0.55111325 0.58863586 0.58863586 0.58863586]
  [0.59115744 0.59115744 0.59115744 0.3951699  0.3951699  0.3951699 ]
  [0.6303138  0.6303138  0.6303138  0.21942244 0.21942244 0.21942244]]], shape: (1, 4, 6)
forward state: [[0.6303138 0.6303138 0.6303138]], shape: (1, 3)
backward state: [[0.7038734 0.7038734 0.7038734]], shape: (1, 3)


In [11]:
# return_state=True: 마지막 시점 정방향 은닉/셀 상태와 역방향 은닉/셀 상태 반환
bilstm = Bidirectional(LSTM(3, return_sequences=False, return_state=True,
                            kernel_initializer=k_init, bias_initializer=b_init, recurrent_initializer=r_init))
hidden_states, forward_h, forward_c, backward_h, backward_c = bilstm(train_X)

print('hidden states: {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('forward state: {}, shape: {}'.format(forward_h, forward_h.shape))
print('backward state: {}, shape: {}'.format(backward_h, backward_h.shape))

hidden states: [[0.6303138 0.6303138 0.6303138 0.7038734 0.7038734 0.7038734]], shape: (1, 6)
forward state: [[0.6303138 0.6303138 0.6303138]], shape: (1, 3)
backward state: [[0.7038734 0.7038734 0.7038734]], shape: (1, 3)
