# 1. 벡터와 행렬
벡터는 크기와 방향을 가지며, 1차원 배열 혹은 리스트로 표현   
행렬은 행과 열로 된 2차원 형상을 가지며, 2차원 배열로 표현   

# 2. 텐서(Tensor)
텐서는 3차원 이상의 배열로 표현되며, 입출력이 복잡해질 때 요구됨

In [1]:
import numpy as np

> **1) 0차원 텐서**   
> 스칼라값은 0차원 텐서

In [2]:
d = np.array(5)
print(d.ndim)
print(d.shape)

0
()


> **2) 1차원 텐서**   
> 벡터는 1차원 텐서  
> 벡터와 텐서의 차원은 다른 개념, 예제는 4차원 벡터이지만 1차원 텐서

In [3]:
d = np.array([1,2,3,4])
print(d.ndim)
print(d.shape)

1
(4,)


> **3) 2차원 텐서**   
> 행렬은 2차원 텐서

In [4]:
d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(d.ndim)
print(d.shape)

2
(3, 4)


> **4) 3차원 텐서**   
> data science 분야 한정으로 3차원 이상 배열을 텐서라 칭함   
> text sequence를 표현하고자 사용   
> 이 경우 텐서는 (samples/batch_size, timesteps, word_dim)으로 구성됨

> 문서1: I like NLP    
> 문서2: I like DL   
> 문서3: DL is AI

> 단어|One-Hot vector
> :--|:--
> I|[1 0 0 0 0 0]
> like|[0 1 0 0 0 0]
> NLP|[0 0 1 0 0 0]
> DL|[0 0 0 1 0 0]
> is|[0 0 0 0 1 0]
> AI|[0 0 0 0 0 1]

> 인공 신경망 모델의 입력으로 사용하고자 각 단어를 벡터화

> [[[1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0]],   
>  [[1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0]],   
>  [[0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 1]]]   
> 이는 (3, 3, 6) 크기 3차원 텐서

In [5]:
d = np.array([
              [[1,2,3,4,5], [6,7,8,9,10], [10,11,12,13,14]],
              [[15,16,17,18,19], [19,20,21,22,23], [23,24,25,26,27]]
            ])
print(d.ndim)
print(d.shape)

3
(2, 3, 5)


> **5) 그 이상의 텐서**   
> n차원 텐서를 배열로 합치면 n+1차원 텐서
> ![more tensors](https://wikidocs.net/images/page/37001/tensor.png "more tensors")

> **6) 케라스에서의 텐서**   
> 입력 크기 인자 input_shape는 (input_length, input_dim)으로 정의   
> 배치 크기를 지정한다면 (batch_size, input_length, input_dim)으로 새 변수 생성

# 3. 벡터와 행렬의 연산
> **1) 벡터와 행렬의 덧셈과 뺄셈**

In [6]:
a = np.array([8,4,5])
b = np.array([1,2,3])
print(a+b)
print(a-b)

[9 6 8]
[7 2 2]


In [7]:
a = np.array([ [10,20,30,40], [50,60,70,80] ])
b = np.array([ [5,6,7,8], [1,2,3,4] ])
print(a+b)
print(a-b)

[[15 26 37 48]
 [51 62 73 84]]
[[ 5 14 23 32]
 [49 58 67 76]]


> **2) 벡터의 내적과 행렬의 곱셈**

In [8]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.dot(a,b))

32


In [9]:
a = np.array([ [1,3], [2,4] ])
b = np.array([ [5,7], [6,8] ])
print(np.matmul(a,b))

[[23 31]
 [34 46]]


# 3. 다중 선형 회귀 행렬 연산으로 이해하기
독립 변수가 n개인 다중 선형 회귀 수식   
$$y = w_{1}x_{1} + w_{2}x_{2} + ... + w_{n}x_{n} + b$$   

이는 가중치 벡터와 입력 벡터의 내적   
데이터가 많을 때는 내적이 아닌 행렬곱으로 표현 가능   
$$y = \begin{bmatrix} x_{1}\\x_{2}\\...\\x_{n}\\ \end{bmatrix}\begin{bmatrix} w_{1} w_{2} ... w_{n}\\ \end{bmatrix} + b$$

# 4. 샘플(Sample)과 특성(Feature)
sample: 데이터의 실제 값들   
feature: 종속변수 예측에 사용되는 독립변수

# 5. 가중치와 편향 행렬 크기 결정
**미니배치 학습**은 전체 데이터를 m개씩 묶어 작은 그룹으로 분할해 여러 번 처리함
$$Y_{m \times j} = X_{m \times n} \times W_{n \times j} + B_{m \times j}$$